# Generated by Django 5.0.1 on 2024-02-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home__page", "0002_visitorlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("visit_time", models.DateTimeField(auto_now_add=True)),
                ("departure_time", models.DateTimeField(blank=True, null=True)),
                (
                    "landing_page",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("time_on_page", models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="VisitorLog",
        ),
    ]
