# Generated by Django 5.0.1 on 2024-02-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home__page", "0003_visitor_delete_visitorlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitor",
            name="landing_page",
            field=models.URLField(blank=True, null=True),
        ),
    ]
