# Generated by Django 5.0.1 on 2024-02-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home__page", "0004_alter_visitor_landing_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="unique_visitors",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
