# Generated by Django 5.0.1 on 2024-02-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home__page", "0005_visitor_unique_visitors"),
    ]

    operations = [
        migrations.CreateModel(
            name="UniqueVisitorCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                (
                    "unique_visitors",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="visitor",
            name="unique_visitors",
        ),
    ]
