# Generated by Django 5.0.1 on 2024-02-05 09:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home__page", "0006_uniquevisitorcount_remove_visitor_unique_visitors"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uniquevisitorcount",
            old_name="unique_visitors",
            new_name="visit_count",
        ),
    ]
