# Generated by Django 5.0.2 on 2024-02-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home__page", "0007_rename_unique_visitors_uniquevisitorcount_visit_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="uniquevisitorcount",
            name="address",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="uniquevisitorcount",
            name="latitude",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="uniquevisitorcount",
            name="longitude",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
